title: Piotr Laskowski
description: "A quiet outlet for nagging thoughts about software engineering."
author: Piotr Laskowski
url: "https://plaskowski.github.io"

permalink: pretty

exclude:
  - README.md
